### ISSUE TITLE
RFMix_PopPhased skipping growing forests

### ISSUE THREAD

**Issue by angelcymak** [slowkoni/rfmix#6]
I am running RFMix version 1.5.4. When I run PopPhased, I would normally see these messages shown on the screen:

Giddyup
Reading files
Number of processors available: 24
Minimum node size: 1
Number of SNPs Read: 22676
Number of SNPs to Exclude: 0
Number left after pruning: 22676
Number of windows: 800
Creating phasings
Done creating phasings
Growing forests
Applying Conditional Random Fields
CRF on individual: 0
CRF on individual: 1
CRF on individual: 2
CRF on individual: 3
CRF on individual: 4
....
CRF on individual: 2180
Checking input...
Done checking input

However, I am having problem with one of the chromosome that the steps from "Growing forests" and "Applying Conditional Random Fields" are skipped without any errors. Could you please advise what may be wrong?

**Comment by slowkoni** [comment]
Hi Angel,

I’m sorry, I’m unable to answer your questions below. I wrote and support RFMIX v2.X available on GitHub under github.com/slowkoni/rfmix <http://github.com/slowkoni/rfmix>. RFMIX 2.X more or less implements the same methodology originally developed by Brian Maples at Stanford during his graduate research. I believe he maintains a website which makes his original final version, 1.5.4 that you refer to below, available somewhere, and obviously, you have found that, but you would have to contact him for help. Unfortunately, I do not have a current email address for him. I think the last few times I tried his old Stanford address (he graduated some years ago) the email just bounced. My stanford email address will also bounce as I no longer work there. 

Please only open GitHub issues/tickets for RFMIX 2.X if they pertain to that version series and source code base, which is completely different than the one Brian originally developed. For 1.5.4, I suggest trying to find Brian on LinkedIn perhaps, he’s out there somewhere. Or, you can try RFMIX 2.X if you are an academic or research institute user. For commercial use including non-profit organizations a license is required, please contact Stanford Office of Technology Licensing for that.

Best,
Koni

**Comment by angelcymak** [comment]
Got it! Thanks Daniel.
