### ISSUE TITLE
map file?

### ISSUE THREAD

**Issue by sariya** [slowkoni/rfmix#8]
I'm using RFmix (v1.4) but that unfortunately dumps core (working on cluster 55G), CHR9. I came across this git repo and thought to give this a try. I compile, make, configure get the rfmix executable.  
I've query .vcf file, I've reference vcf file but I don't know about following two input parameters on how to generate, or the format

```
  -m <string>, --sample-map=<string>   (required)
      Reference panel sample population classification map  (required)
   -g <string>, --genetic-map=<string>  (required)
      Genetic map file                                      (required)

```
Can you help?

RFMIX v2.03-r0 
```
uname  -a
Linux node24 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

```

**Comment by mocksu** [comment]
It's in the manual on this site:

The genetic map file is tab delimited text containing at least 3 columns. The first 3 columns are intepreted as chromosome, physical position in bp, genetic position in cM. Any number of columns or other information may follow, it is ignored. The chromosome column is a string token (which may be an string of digits) that must match those used in the VCF/BCF inputs. The genetic map file should contain the map for the entire genome (all chromosomes). Blank lines and lines beginning with a '#' are ignored.

The sample map file specifies which subpopulation each reference sample represents. It is tab delimited text with at least two columns. The first column gives the sample name or identifier, which must match the one used in the reference VCF/BCF. The second column is a string naming a subpopulation and may contain spaces (e.g., "European", or "East African").

**Comment by sariya** [comment]
Thank you for your reply.
